In [1]:
import pandas as pd
import datetime as dt

In [2]:
df_grower_prices = pd.read_csv("Grower_Prices_VIZREADY_countrynameupdated.csv")

In [3]:
df_exchange = pd.read_csv("../exchange_rates_VIZREADY.csv")

In [4]:
df_grower_prices.drop(columns=['Unnamed: 0','Unnamed: 0.1','Unnamed: 0.1.1'], inplace=True)

In [5]:
df_grower_prices.head()

,Country,Continents,Unit,Country_Code,Weight,Type,Type of Coffee,Date,Price,unit_price(/kg)
0,Burundi,Africa,kg,BIF,1,P,Arabica,Jan-1963,20.0,20.00
1,Cameroon,Africa,kg,XAF,1,G,Robusta,Jan-1963,90.3,90.30
2,Côte d'Ivoire,Africa,kg,XAF,1,G,Robusta,Jan-1963,80.0,80.00
3,Kenya,Africa,kg,KES,50,G,Arabica,Jan-1963,274.0,5.48
4,"Madagascar, Rep. of",Africa,kg,MGF,1,G,Robusta,Jan-1963,83.0,83.00

In [6]:
df_exchange.drop(columns='Unnamed: 0', inplace=True)

In [7]:
df_exchange.rename(columns=({'Date':'Year'}), inplace=True)

In [8]:
df_grower_prices['Datetime'] = pd.to_datetime(df_grower_prices["Date"], format='%b-%Y')

In [9]:
df_grower_prices['Year'] = [d.year for d in df_grower_prices['Datetime']]
df_grower_prices['Month'] = [d.month for d in df_grower_prices['Datetime']]

In [10]:
df_grower_prices.drop(columns=['Date'], inplace=True)

In [11]:
df_grower_prices

,Country,Continents,Unit,Country_Code,Weight,Type,Type of Coffee,Price,unit_price(/kg),Datetime,Year,Month
0,Burundi,Africa,kg,BIF,1,P,Arabica,20.00,20.00,1963-01-01,1963,1
1,Cameroon,Africa,kg,XAF,1,G,Robusta,90.30,90.30,1963-01-01,1963,1
2,Côte d'Ivoire,Africa,kg,XAF,1,G,Robusta,80.00,80.00,1963-01-01,1963,1
3,Kenya,Africa,kg,KES,50,G,Arabica,274.00,5.48,1963-01-01,1963,1
4,"Madagascar, Rep. of",Africa,kg,MGF,1,G,Robusta,83.00,83.00,1963-01-01,1963,1
...,...,...,...,...,...,...,...,...,...,...,...,...
24817,Honduras,Central America & Mexico,SQ,HNL,1,G,Arabica,1857.35,40.47,2018-12-01,2018,12
24818,Bolivia,South America,kg,BOB,1,G,Arabica,83.62,83.62,2018-12-01,2018,12
24819,Brazil,South America,kg,BRL,60,G,Arabica,420.32,7.01,2018-12-01,2018,12
24820,Brazil,South America,kg,BRL,60,G,Robusta,309.44,5.16,2018-12-01,2018,12
24821,Colombia,South America,kg,COP,125,P,Arabica,726825.00,5814.60,2018-12-01,2018,12

In [15]:
df_growers_merged = pd.merge(df_grower_prices, df_exchange, on=['Country', 'Year'])

In [16]:
df_growers_merged.to_csv("growers_MERGED_VIZREADY.csv")

In [18]:
df_exchange.to_csv("../exchange_merge_OPTIMIZED.csv")