In [1]:
import pandas as pd
import numpy as np
import os
import glob

# [ E ] xtract

In [51]:
# Read xcel using pandas
path = '../GrowerPrices.xlsx'
xl = pd.read_excel(path, sheet_name = None)

In [54]:
# Combine rows igoring index
df = pd.concat(xl, ignore_index=True)

In [55]:
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51
0,Prices Paid to Growers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,in Current Terms,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,(National Currency),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Country,NaN,Type of Coffee,Jan-63,Feb-63,Mar-63,Apr-63,May-63,Jun-63,Jul-63,...,Apr-66,May-66,Jun-66,Jul-66,Aug-66,Sep-66,Oct-66,Nov-66,Dec-66,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
755,Bolivia (Plurinational State of),South America,(BOB/kg : G),Arabica,44.13,55.37,35.88,26.45,0,33.5,...,101.55,38.43,31.06,36.06,46.28,38.98,37.15,67.33,105.78,83.62
756,Brazil,South America,(BRL/60kg : G),Arabica,465.93,459.99,447.1,445.69,421.95,424.02,...,429.82,430.71,451.02,452.52,439.25,421.16,415.39,441.23,441.59,420.32
757,Brazil,South America,(BRL/60kg : G),Robusta,283.29,299.58,303.44,295.88,290.33,301.03,...,305.56,320.05,330.79,335.39,332.39,319.26,319.38,331.71,332.33,309.44
758,Colombia,South America,(COP/125kg : P),Arabica,771788,721559,683972,685220,632156,671341,...,729855,714440,753978,745381,717045,685000,684211,793130,802929,726825
759,Peru,South America,(PEN/kg : P),Arabica,5.85,6.13,5.53,6.52,6.3,6.48,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# [ T ] ransform

In [4]:
# Quick preview
df.head()

,Country,Continents,Currency_Type,Type of Coffee,Jan-63,Feb-63,Mar-63,Apr-63,May-63,Jun-63,...,Mar-18,Apr-18,May-18,Jun-18,Jul-18,Aug-18,Sep-18,Oct-18,Nov-18,Dec-18
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Burundi,Africa,(BIF/kg : P),Arabica,20.0,20.0,20.0,20.5,20.5,20.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Cameroon,Africa,(XAF/kg : G),Robusta,90.3,90.3,90.3,90.3,90.3,90.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Côte d'Ivoire,Africa,(XAF/kg : G),Robusta,80.0,80.0,80.0,80.0,80.0,80.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Check col headers
df.columns

Index(['Country', 'Continents', 'Currency_Type', 'Type of Coffee', 'Jan-63',
       'Feb-63', 'Mar-63', 'Apr-63', 'May-63', 'Jun-63',
       ...
       'Mar-18', 'Apr-18', 'May-18', 'Jun-18', 'Jul-18', 'Aug-18', 'Sep-18',
       'Oct-18', 'Nov-18', 'Dec-18'],
      dtype='object', length=628)

In [6]:
# Check how many values per col
df.count()

Country           540
Continents        540
Currency_Type     540
Type of Coffee    540
Jan-63              8
                 ...
Aug-18             18
Sep-18             16
Oct-18             14
Nov-18             17
Dec-18             17
Length: 628, dtype: int64

In [7]:
# Check data types
df.dtypes

Country            object
Continents         object
Currency_Type      object
Type of Coffee     object
Jan-63            float64
                   ...
Aug-18             object
Sep-18             object
Oct-18             object
Nov-18             object
Dec-18             object
Length: 628, dtype: object

In [8]:
# Convert all values to float
cols = df.loc[:,'Jan-63':'Dec-18'].columns
df[cols] = df[cols].apply(pd.to_numeric, errors='coerce')

In [9]:
df.dtypes

Country            object
Continents         object
Currency_Type      object
Type of Coffee     object
Jan-63            float64
                   ...
Aug-18            float64
Sep-18            float64
Oct-18            float64
Nov-18            float64
Dec-18            float64
Length: 628, dtype: object

In [10]:
# Check for missing index country values
df.isna().sum()

Country           113
Continents        113
Currency_Type     113
Type of Coffee    113
Jan-63            645
                 ...
Aug-18            644
Sep-18            646
Oct-18            648
Nov-18            645
Dec-18            645
Length: 628, dtype: int64

In [11]:
# Remove those empty rows
df1 = df.dropna(subset=['Country'])
# # Recheck
df1.isna().sum()

Country             0
Continents          0
Currency_Type       0
Type of Coffee      0
Jan-63            532
                 ...
Aug-18            531
Sep-18            533
Oct-18            535
Nov-18            532
Dec-18            532
Length: 628, dtype: int64

In [12]:
# Drop rows with completely missing data
df1 = df1.dropna(how='all')

In [13]:
df1

,Country,Continents,Currency_Type,Type of Coffee,Jan-63,Feb-63,Mar-63,Apr-63,May-63,Jun-63,...,Mar-18,Apr-18,May-18,Jun-18,Jul-18,Aug-18,Sep-18,Oct-18,Nov-18,Dec-18
2,Burundi,Africa,(BIF/kg : P),Arabica,20.0,20.0,20.0,20.5,20.5,20.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Cameroon,Africa,(XAF/kg : G),Robusta,90.3,90.3,90.3,90.3,90.3,90.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Côte d'Ivoire,Africa,(XAF/kg : G),Robusta,80.0,80.0,80.0,80.0,80.0,80.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Ethiopia,Africa,(ETB/17kg : G),Arabica,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Gabon,Africa,(XAF/kg : D),Robusta,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
647,Bolivia (Plurinational State of),South America,(BOB/kg : G),Arabica,NaN,NaN,NaN,NaN,NaN,NaN,...,101.55,38.43,31.06,36.06,46.28,38.98,37.15,67.33,105.78,83.62
648,Brazil,South America,(BRL/60kg : G),Arabica,NaN,NaN,NaN,NaN,NaN,NaN,...,429.82,430.71,451.02,452.52,439.25,421.16,415.39,441.23,441.59,420.32
649,Brazil,South America,(BRL/60kg : G),Robusta,NaN,NaN,NaN,NaN,NaN,NaN,...,305.56,320.05,330.79,335.39,332.39,319.26,319.38,331.71,332.33,309.44
650,Colombia,South America,(COP/125kg : P),Arabica,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
651,Peru,South America,(PEN/kg : P),Arabica,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
# Iterate over currency and remove extraneous elements
def hasNumbers(inputString):
    return any(char.isdigit() for char in inputString)

s = df1['Currency_Type']

new_s = []
num = []
count = 0

for elt in s:
    elt = elt.replace('(',"")
    elt = elt.replace(')',"")
    elt = elt.replace('/'," ")
    elt = elt.replace(': ',"")
    
    if hasNumbers(elt):
        count += 1
        num.append(elt)
    else:
        num.append(elt.replace(elt,'nan'))
        
    new_s.append(elt)
    
df1['Currency_Type'] = new_s
df1.head()

,Country,Continents,Currency_Type,Type of Coffee,Jan-63,Feb-63,Mar-63,Apr-63,May-63,Jun-63,...,Mar-18,Apr-18,May-18,Jun-18,Jul-18,Aug-18,Sep-18,Oct-18,Nov-18,Dec-18
2,Burundi,Africa,BIF kg P,Arabica,20.0,20.0,20.0,20.5,20.5,20.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Cameroon,Africa,XAF kg G,Robusta,90.3,90.3,90.3,90.3,90.3,90.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Côte d'Ivoire,Africa,XAF kg G,Robusta,80.0,80.0,80.0,80.0,80.0,80.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Ethiopia,Africa,ETB 17kg G,Arabica,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Gabon,Africa,XAF kg D,Robusta,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df1[['Country_Code','Unit','Type', 'Blank']] = df1['Currency_Type'].str.split(' ',expand=True)

df1.head(50)

,Country,Continents,Currency_Type,Type of Coffee,Jan-63,Feb-63,Mar-63,Apr-63,May-63,Jun-63,...,Jul-18,Aug-18,Sep-18,Oct-18,Nov-18,Dec-18,Country_Code,Unit,Type,Blank
2,Burundi,Africa,BIF kg P,Arabica,20.00,20.00,20.00,20.50,20.50,20.50,...,NaN,NaN,NaN,NaN,NaN,NaN,BIF,kg,P,None
3,Cameroon,Africa,XAF kg G,Robusta,90.30,90.30,90.30,90.30,90.30,90.30,...,NaN,NaN,NaN,NaN,NaN,NaN,XAF,kg,G,None
4,Côte d'Ivoire,Africa,XAF kg G,Robusta,80.00,80.00,80.00,80.00,80.00,80.00,...,NaN,NaN,NaN,NaN,NaN,NaN,XAF,kg,G,None
5,Ethiopia,Africa,ETB 17kg G,Arabica,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ETB,17kg,G,None
6,Gabon,Africa,XAF kg D,Robusta,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,XAF,kg,D,None
7,Kenya,Africa,KES 50kg G,Arabica,274.00,274.00,274.00,274.00,274.00,274.00,...,NaN,NaN,NaN,NaN,NaN,NaN,KES,50kg,G,None
8,Madagascar,Africa,MGF kg G,Robusta,83.00,83.00,83.00,83.00,83.00,83.00,...,NaN,NaN,NaN,NaN,NaN,NaN,MGF,kg,G,None
9,Togo,Africa,XAF kg G,Robusta,65.00,65.00,65.00,65.00,65.00,65.00,...,NaN,NaN,NaN,NaN,NaN,NaN,XAF,kg,G,None
12,Costa Rica,Central America & Mexico,CRC SQ G,Arabica,229.22,229.22,229.22,229.22,229.22,229.22,...,NaN,NaN,NaN,NaN,NaN,NaN,CRC,SQ,G,None
13,Guatemala,Central America & Mexico,GTQ SQ G,Arabica,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,GTQ,SQ,G,None
16,Brazil,South America,CRZ 60kg G,Arabica,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,CRZ,60kg,G,None
17,Colombia,South America,COP 125kg P,Arabica,555.52,555.52,555.52,555.52,555.52,555.52,...,NaN,NaN,NaN,NaN,NaN,NaN,COP,125kg,P,None
18,Venezuela,South America,VEB SQ G,Arabica,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,VEB,SQ,G,None
22,Burundi,Africa,BIF kg P,Arabica,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,BIF,kg,P,None
23,Cameroon,Africa,XAF kg G,Robusta,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,XAF,kg,G,None
24,Côte d'Ivoire,Africa,XAF kg G,Robusta,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,XAF,kg,G,None
25,Ethiopia,Africa,ETB 17kg G,Arabica,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ETB,17kg,G,None
26,Gabon,Africa,XAF kg D,Robusta,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,XAF,kg,D,None
27,Kenya,Africa,KES 50kg G,Arabica,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,KES,50kg,G,None
28,Madagascar,Africa,MGF kg G,Robusta,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,MGF,kg,G,None
29,Togo,Africa,XAF kg G,Robusta,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,XAF,kg,G,None
30,Uganda,Africa,UGS kg G,Arabica,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,UGS,kg,G,None
33,Costa Rica,Central America & Mexico,CRC SQ G,Arabica,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,CRC,SQ,G,None
34,Cuba,Central America & Mexico,CUP 28lb F,Arabica,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,CUP,28lb,F,None
35,Guatemala,Central America & Mexico,GTQ SQ G,Arabica,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,GTQ,SQ,G,None
38,Brazil,South America,CRZ 60kg G,Arabica,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,CRZ,60kg,G,None
39,Colombia,South America,COP 125kg P,Arabica,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,COP,125kg,P,None
40,Venezuela,South America,VEB SQ G,Arabica,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,VEB,SQ,G,None
44,Angola,Africa,ANK kg D,Robusta,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ANK,kg,D,None
45,Benin,Africa,XAF kg G,Robusta,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,XAF,kg,G,None
46,Burundi,Africa,BIF kg P,Arabica,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,BIF,kg,P,None
47,Cameroon,Africa,XAF kg G,Robusta,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,XAF,kg,G,None
48,Central African Republic,Africa,XAF kg G,Robusta,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,XAF,kg,G,None
49,Congo,Africa,XAF kg G,Robusta,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,XAF,kg,G,None
50,Côte d'Ivoire,Africa,XAF kg G,Robusta,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,XAF,kg,G,None
51,Democratic Republic of Congo,Africa,ZAA kg P,Robusta,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ZAA,kg,P,None
52,Ethiopia,Africa,ETB 17kg G,Arabica,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ETB,17kg,G,None
53,Gabon,Africa,XAF kg D,Robusta,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,XAF,kg,D,None
54,Ghana,Africa,GHC 60kg G,Robusta,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,GHC,60kg,G,None
55,Guinea,Africa,GNF kg G,Robusta,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,GNF,kg,G,None
56,Kenya,Africa,KES 50kg G,Arabica,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,KES,50kg,G,None
57,Liberia,Africa,LRD,Robusta,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,LRD,,None,None
58,Madagascar,Africa,MGF kg G,Robusta,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,MGF,kg,G,None
59,Nigeria,Africa,NGN m Ton G,Robusta,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NGN,m,Ton,G
60,Rwanda,Africa,RWF kg P,Arabica,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,RWF,kg,P,None
61,Sierra Leone,Africa,SLL L Ton G,Robusta,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,SLL,L,Ton,G
62,Tanzania,Africa,TZS kg P,Arabica,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,TZS,kg,P,None
63,Togo,Africa,XAF kg G,Robusta,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,XAF,kg,G,None
64,Uganda,Africa,UGS kg G,Arabica,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,UGS,kg,G,None
65,Uganda,Africa,UGS kg G,Robusta,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,UGS,kg,G,None

In [16]:
cols = list(df1)

# move the column to head of list using index, pop and insert
cols.insert(3, cols.pop(cols.index('Type')))
cols.insert(3, cols.pop(cols.index('Unit')))
cols.insert(3, cols.pop(cols.index('Currency_Type')))
cols.insert(3, cols.pop(cols.index('Country_Code')))
df2 = df1.loc[:,cols]
df2['Currency_Type'] = df2['Currency_Type'].str.extract('(\d+)')
df2['Unit'] = df2['Unit'].str.extract('(\D+)')
df2.rename(columns={'Currency_Type':'Weight'}, inplace=True)
df2.drop(columns='Blank', inplace=True)
df2.fillna(value={'Weight':1}, inplace=True)

In [17]:
### Where I left off. Just completed getting everything cleaned up. Quick look over and should be able to
### start slicing

In [18]:
df2.reset_index(drop=True, inplace=True)

In [45]:
df2

,Country,Continents,Unit,Country_Code,Weight,Type,Type of Coffee,Jan-1963,Feb-1963,Mar-1963,...,Mar-2018,Apr-2018,May-2018,Jun-2018,Jul-2018,Aug-2018,Sep-2018,Oct-2018,Nov-2018,Dec-2018
0,Burundi,Africa,kg,BIF,1,P,Arabica,20.0,20.0,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Cameroon,Africa,kg,XAF,1,G,Robusta,90.3,90.3,90.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Côte d'Ivoire,Africa,kg,XAF,1,G,Robusta,80.0,80.0,80.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Ethiopia,Africa,kg,ETB,17,G,Arabica,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Gabon,Africa,kg,XAF,1,D,Robusta,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535,Bolivia (Plurinational State of),South America,kg,BOB,1,G,Arabica,NaN,NaN,NaN,...,101.55,38.43,31.06,36.06,46.28,38.98,37.15,67.33,105.78,83.62
536,Brazil,South America,kg,BRL,60,G,Arabica,NaN,NaN,NaN,...,429.82,430.71,451.02,452.52,439.25,421.16,415.39,441.23,441.59,420.32
537,Brazil,South America,kg,BRL,60,G,Robusta,NaN,NaN,NaN,...,305.56,320.05,330.79,335.39,332.39,319.26,319.38,331.71,332.33,309.44
538,Colombia,South America,kg,COP,125,P,Arabica,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
539,Peru,South America,kg,PEN,1,P,Arabica,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
lst_cols = []

for col in df2.loc[:,'Jan-63':].columns:
    if 'unnamed' not in col.lower():
        lst_cols.append(col)

In [21]:
# Clean up dates to remove issue of partial YY
s_dates = pd.Series(lst_cols)
s_dates_spl = s_dates.str.split("-",expand=True)

for i, elt in enumerate(s_dates_spl[1]):
    if int(elt) <= 99 and int(elt) > 18:
        s_dates_spl.at[i,1] = "19" + elt
    else:
        s_dates_spl.at[i,1] = "20" + elt
        
s_dates = s_dates_spl[0].str.cat(s_dates_spl[1], join='right', sep='-')

In [22]:
#  inplace replace col names to avoid date confusion on last digits
for i, col in enumerate(df2.loc[:,'Jan-63':].columns):
    df2.rename(columns={str(col) : str(s_dates[i])}, inplace = True)

In [23]:
df2.head()

,Country,Continents,Unit,Country_Code,Weight,Type,Type of Coffee,Jan-1963,Feb-1963,Mar-1963,...,Mar-2018,Apr-2018,May-2018,Jun-2018,Jul-2018,Aug-2018,Sep-2018,Oct-2018,Nov-2018,Dec-2018
0,Burundi,Africa,kg,BIF,1,P,Arabica,20.0,20.0,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Cameroon,Africa,kg,XAF,1,G,Robusta,90.3,90.3,90.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Côte d'Ivoire,Africa,kg,XAF,1,G,Robusta,80.0,80.0,80.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Ethiopia,Africa,kg,ETB,17,G,Arabica,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Gabon,Africa,kg,XAF,1,D,Robusta,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
lst_cols = []

for col in df2.loc[:,'Jan-1963':].columns:
    if 'unnamed' not in col.lower():
        lst_cols.append(col)

In [25]:
df_test = pd.melt(df2, id_vars=['Country', 'Continents','Unit','Country_Code','Weight','Type','Type of Coffee'], value_vars=lst_cols).rename(columns={'variable':'Date','value':'Price'})

In [26]:
df_test.sort_values('Country')

,Country,Continents,Unit,Country_Code,Weight,Type,Type of Coffee,Date,Price
239439,Angola,Africa,kg,ANK,1,D,Robusta,Dec-2003,NaN
93586,Angola,Africa,kg,ANK,1,D,Robusta,Jun-1977,NaN
23248,Angola,Africa,kg,ANK,1,D,Robusta,Aug-1966,NaN
174390,Angola,Africa,kg,AOA,1,D,Robusta,Nov-1993,NaN
174389,Angola,Africa,kg,AOA,1,D,Arabica,Nov-1993,NaN
...,...,...,...,...,...,...,...,...,...
48304,Zimbabwe,Africa,m,ZWD,1,Ton,Arabica,Jun-1970,NaN
235091,Zimbabwe,Africa,m,ZWD,1,Ton,Arabica,Apr-2003,NaN
48251,Zimbabwe,Africa,m,ZWD,1,Ton,Arabica,Jun-1970,NaN
210902,Zimbabwe,Africa,m,ZWD,1,Ton,Arabica,Jul-1999,NaN
10991,Zimbabwe,Africa,m,ZWD,1,Ton,Arabica,Sep-1964,NaN

In [27]:
# .rename(columns=({'variable':'Date','value':'Price'}))

In [28]:
df_test.to_csv('GrowerPrices_CLEANED.csv')

In [39]:
# df_test[df_test['Date'] == 'Dec-1989']

Empty DataFrame
Columns: [Country, Continents, Unit, Country_Code, Weight, Type, Type of Coffee, Date, Price]
Index: []